
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.



array = [1, 2]


while array.last <= 4000000 do 
	new = array[-1] + array[-2]
	array << new
end

sum = 0
array.each do |n|
	if (n % 2 == 0)
		sum += n
	end
end

puts sum

